project:
  type: website
  render:
    - "*.qmd"

website:
  title: "Aprendizado Descritivo"
  navbar:
    title: false
    left:
      - href: index.qmd
        text: Home
      - text: "Seminário 1"
        menu:
            - seminario1/artigo1.qmd
            - seminario1/artigo2.qmd
            - seminario1/artigo3.qmd
        
      - text: "Seminário 2"
        menu:
            - seminario2/artigo4.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true
#    linkcolor: "#666666"
    
execute:
  freeze: true    